# Generated by Django 4.2.5 on 2023-11-05 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_mgt', '0004_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
    ]
