# Generated by Django 4.2.5 on 2023-11-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_mgt', '0007_alter_task_assignee_alter_task_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=models.CharField(blank=True, max_length=85, null=True),
        ),
    ]
