# Generated by Django 4.2.5 on 2023-11-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_mgt', '0008_alter_task_assignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.BooleanField(blank=True, default=False, help_text='0=default, 1=Hidden'),
        ),
    ]
