# Generated by Django 4.2.5 on 2023-11-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_mgt', '0009_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
